# Generated by Django 3.2.5 on 2021-07-09 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('idNoticia', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Id Noticia')),
                ('titulo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Titulo')),
                ('resumen', models.CharField(max_length=30, verbose_name='Resumen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
